/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper */

#ifndef _Included_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
#define _Included_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL
Java_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper_native_1init(JNIEnv *, jobject);

/*
 * Class:     com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
 * Method:    native_open
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper_native_1open
        (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
 * Method:    native_x264_encode
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/Float;II)I
 */
JNIEXPORT jint JNICALL Java_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper_native_1x264_1encode
        (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jint, jobject, jint, jint);

/*
 * Class:     com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
 * Method:    native_ksy265_encoder
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/Float;II)I
 */
JNIEXPORT jint JNICALL Java_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper_native_1ksy265_1encoder
        (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jint, jobject, jint, jint);

/*
 * Class:     com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
 * Method:    native_get_real_fps
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL
Java_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper_native_1get_1real_1fps(JNIEnv *,
                                                                                      jobject, jlong);

/*
 * Class:     com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper
 * Method:    native_get_encoded_frame_num
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_com_ksyun_media_ksy265codec_demo_encoder_EncoderWrapper_native_1get_1encoded_1frame_1num(
        JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
